### ISSUE TITLE
Crash with FAPI 42.x on Quilt Loader

### ISSUE THREAD

**Issue by QPCrummer** [TISUnion/Carpet-TIS-Addition#43]
https://pastebin.com/dGN6DEz8

**Comment by Fallen-Breath** [comment]
It works for me to start the server with fabric loader with these mods:

- java 17, minecraft 1.17.1
- fabric-carpet-1.17.1-1.4.54 v211117
- carpet-tis-addition-mc1.17.1-v1.25.0+build.767
- fabric-api-0.42.1+1.17

You can try to remove other unrelated mods to see if it's conflicting with quilt loader, or other mods

And since quilt is another modloader, if it's quilt's issue I probably won't intendly to fix it unless the changes to fix that is obvious

**Comment by QPCrummer** [comment]
I found the issue. It was Fabric Proxy Lite that was causing the issues. Thanks
