### ISSUE TITLE
Incompatible with VMP mod

### ISSUE THREAD

**Issue by Dreeam-qwq** [TISUnion/Carpet-TIS-Addition#52]
Server can't lanuch with Carpet-tis-addition + VMP mod

Version:
- Java: `microsoft-jdk-17.0.1.12.1`
- `1.18.1`
- Fabric Loader: `0.12.12`
- Fabric api: `0.45.0+1.18`
- Carpet-tis-addition: `v1.28.1`
- Carpet: `1.4.56+v211130`
- Vmp: [`0.2.0+beta.2.20-all`](https://github.com/RelativityMC/VMP-fabric)

Error:
`https://paste.gg/p/anonymous/dbefca6b63c644f18f9b5ee09d8f5ea1`

**Comment by Fallen-Breath** [comment]
Seems like vmp overwrote the method `forEach(Lnet/minecraft/util/math/Box;Ljava/util/function/Consumer;)V` with intended larger priority value 1050, resulting in its overwritting getting applied later so it conflicts. So I'll suggest you to make an issue there. Since vmp overwrites the method, it already has a great possibility to be incompatible with other mods, and I can't guarantee that it will be possible to make it compatible

https://github.com/RelativityMC/VMP-fabric/blob/a23e665d3bec1aa7a30ccfba3e65b631e42b5fe7/src/main/java/com/ishland/vmp/mixins/entity/iteration/MixinEntityTrackingSection.java#L29-L30

**Comment by Dreeam-qwq** [comment]
The problem solved.
