### ISSUE TITLE
Suggestion: add /place to the list of commands that get removed by opPlayerNoCheat rule

### ISSUE THREAD

**Issue by nogutsnoglory69** [TISUnion/Carpet-TIS-Addition#71]

**Comment by Fallen-Breath** [comment]
What's the usage of that? Why did you choose the seem-to-be-irrelevant name `/place`. 

Noted that `/place` is also a vanilla command, and the command list you want is shown in the description of the rule `opPlayerNoCheat`

**Comment by nogutsnoglory69** [comment]
This rule is supposed to prevent accidental cheating, right? So to me it seems like that command should also be removed by that rule since it's very easy to autocomplete that command instead of /player. 

If you don't want to hide that command through the opplayernocheat rule, may I suggest adding a seperate rule to disable that command? I just updated from 1.17 a few days ago and I keep autocompleting /place instead of the /player command all the time and it's very annoying.

**Comment by Fallen-Breath** [comment]
Ah you mean make the vanilla `/place` command disabled too. I thought you want to introduce a `/place` command to display what is disabled via the rule

Back to the suggestion itself, if there isn't any way to like one-key execute the `/place` command, I don't think it's necessary enough to disable the command just because it loves to pop up in other command suggestions. `/place` & `/player` is not the special case, since it still needs you to enter commands in your chatbar and press enter manually before executing the command. You can always accidentally execute much more commands if you don't check what you have input. If I did that people will keep asking me to add some other commands (maybe added by scarpet so the command name can be customized enough) to be disabled. 

For the workaround, you can try [tweakermore's `prioritizedcommandsuggestions` option](https://github.com/Fallen-Breath/tweakermore/blob/stable/docs/document-en_us.md#prioritizedcommandsuggestions) to make the `/player` command is always on the top of the list

**Comment by nogutsnoglory69** [comment]
I wasn't aware that tweakermore has that feature, I went ahead and enabled that. That does the job, thank you very much!
